DELETE FROM `tes_referencia`;
ALTER TABLE `tes_referencia` AUTO_INCREMENT = 1;
DELETE FROM `seg_terceros`;
ALTER TABLE `seg_terceros` AUTO_INCREMENT = 1;
DELETE FROM `ctb_doc`;
ALTER TABLE `ctb_doc` AUTO_INCREMENT = 1;
DELETE FROM `ctb_factura`;
ALTER TABLE `ctb_factura` AUTO_INCREMENT = 1;
DELETE FROM `ctb_pgcp`;
ALTER TABLE `ctb_pgcp` AUTO_INCREMENT = 1;
DELETE FROM `ctb_libaux`;
ALTER TABLE `ctb_libaux` AUTO_INCREMENT = 1;
DELETE FROM `ctt_modalidad`;
ALTER TABLE `ctt_modalidad` AUTO_INCREMENT = 1;
DELETE FROM `tb_tipo_contratacion`;
ALTER TABLE `tb_tipo_contratacion` AUTO_INCREMENT = 1;
DELETE FROM `tb_tipo_bien_servicio`;
ALTER TABLE `tb_tipo_bien_servicio` AUTO_INCREMENT = 1;
DELETE FROM `pto_presupuestos`;
ALTER TABLE `pto_presupuestos` AUTO_INCREMENT = 1;
DELETE FROM `pto_cdp`;
ALTER TABLE `pto_cdp` AUTO_INCREMENT = 1;
DELETE FROM `ctt_adquisiciones`;
ALTER TABLE `ctt_adquisiciones` AUTO_INCREMENT = 1;
DELETE FROM `ctt_bien_servicio`;
ALTER TABLE `ctt_bien_servicio` AUTO_INCREMENT = 1;
DELETE FROM `ctt_adquisicion_detalles`;
ALTER TABLE `ctt_adquisicion_detalles` AUTO_INCREMENT = 1;
DELETE FROM `ctt_clasificacion_bn_sv`;
ALTER TABLE `ctt_clasificacion_bn_sv` AUTO_INCREMENT = 1;
DELETE FROM `ctt_contratos`;
ALTER TABLE `ctt_contratos` AUTO_INCREMENT = 1;
DELETE FROM `tb_centros_costo`;
ALTER TABLE `tb_centros_costo` AUTO_INCREMENT = 1;
DELETE FROM `tb_centro_costo_x_sede`;
ALTER TABLE `tb_centro_costo_x_sede` AUTO_INCREMENT = 1;
DELETE FROM `ctt_destino_contrato`;
ALTER TABLE `ctt_destino_contrato` AUTO_INCREMENT = 1;
DELETE FROM `ctt_escala_honorarios`;
ALTER TABLE `ctt_escala_honorarios` AUTO_INCREMENT = 1;
DELETE FROM `ctt_estado_adq`;
ALTER TABLE `ctt_estado_adq` AUTO_INCREMENT = 1;
DELETE FROM `ctt_estudios_previos`;
ALTER TABLE `ctt_estudios_previos` AUTO_INCREMENT = 1;
DELETE FROM `tb_polizas`;
ALTER TABLE `tb_polizas` AUTO_INCREMENT = 1;
DELETE FROM `ctt_garantias_compra`;
ALTER TABLE `ctt_garantias_compra` AUTO_INCREMENT = 1;
DELETE FROM `ctt_novedad_adicion_prorroga`;
ALTER TABLE `ctt_novedad_adicion_prorroga` AUTO_INCREMENT = 1;
DELETE FROM `ctt_novedad_cesion`;
ALTER TABLE `ctt_novedad_cesion` AUTO_INCREMENT = 1;
DELETE FROM `ctt_novedad_liquidacion`;
ALTER TABLE `ctt_novedad_liquidacion` AUTO_INCREMENT = 1;
DELETE FROM `ctt_novedad_suspension`;
ALTER TABLE `ctt_novedad_suspension` AUTO_INCREMENT = 1;
DELETE FROM `ctt_novedad_reinicio`;
ALTER TABLE `ctt_novedad_reinicio` AUTO_INCREMENT = 1;
DELETE FROM `ctt_novedad_terminacion`;
ALTER TABLE `ctt_novedad_terminacion` AUTO_INCREMENT = 1;
DELETE FROM `fin_maestro_doc`;
ALTER TABLE `fin_maestro_doc` AUTO_INCREMENT = 1;
DELETE FROM `fin_respon_doc`;
ALTER TABLE `fin_respon_doc` AUTO_INCREMENT = 1;
DELETE FROM `nom_afp`;
ALTER TABLE `nom_afp` AUTO_INCREMENT = 1;
DELETE FROM `nom_arl`;
ALTER TABLE `nom_arl` AUTO_INCREMENT = 1;
DELETE FROM `nom_cargo_empleado`;
ALTER TABLE `nom_cargo_empleado` AUTO_INCREMENT = 1;
DELETE FROM `nom_causacion`;
ALTER TABLE `nom_causacion` AUTO_INCREMENT = 1;
DELETE FROM `nom_incremento_salario`;
ALTER TABLE `nom_incremento_salario` AUTO_INCREMENT = 1;
DELETE FROM `nom_retroactivos`;
ALTER TABLE `nom_retroactivos` AUTO_INCREMENT = 1;
DELETE FROM `nom_nominas`;
ALTER TABLE `nom_nominas` AUTO_INCREMENT = 1;
DELETE FROM `nom_cdp_empleados`;
ALTER TABLE `nom_cdp_empleados` AUTO_INCREMENT = 1;
DELETE FROM `nom_conceptos_liquidacion`;
ALTER TABLE `nom_conceptos_liquidacion` AUTO_INCREMENT = 1;
DELETE FROM `nom_conceptosxvigencia`;
ALTER TABLE `nom_conceptosxvigencia` AUTO_INCREMENT = 1;
DELETE FROM `nom_consecutivo_viaticos`;
ALTER TABLE `nom_consecutivo_viaticos` AUTO_INCREMENT = 1;
DELETE FROM `tb_bancos`;
ALTER TABLE `tb_bancos` AUTO_INCREMENT = 1;
DELETE FROM `tb_tipo_cta`;
ALTER TABLE `tb_tipo_cta` AUTO_INCREMENT = 1;
DELETE FROM `nom_tipo_contrato`;
ALTER TABLE `nom_tipo_contrato` AUTO_INCREMENT = 1;
DELETE FROM `nom_subtipo_empl`;
ALTER TABLE `nom_subtipo_empl` AUTO_INCREMENT = 1;
DELETE FROM `nom_estado`;
ALTER TABLE `nom_estado` AUTO_INCREMENT = 1;
DELETE FROM `nom_tipo_empleado`;
ALTER TABLE `nom_tipo_empleado` AUTO_INCREMENT = 1;
DELETE FROM `nom_empleado`;
ALTER TABLE `nom_empleado` AUTO_INCREMENT = 1;
DELETE FROM `nom_contratos_empleados`;
ALTER TABLE `nom_contratos_empleados` AUTO_INCREMENT = 1;
DELETE FROM `nom_sindicatos`;
ALTER TABLE `nom_sindicatos` AUTO_INCREMENT = 1;
DELETE FROM `nom_cuota_sindical`;
ALTER TABLE `nom_cuota_sindical` AUTO_INCREMENT = 1;
DELETE FROM `nom_juzgados`;
ALTER TABLE `nom_juzgados` AUTO_INCREMENT = 1;
DELETE FROM `nom_tipo_embargo`;
ALTER TABLE `nom_tipo_embargo` AUTO_INCREMENT = 1;
DELETE FROM `nom_embargos`;
ALTER TABLE `nom_embargos` AUTO_INCREMENT = 1;
DELETE FROM `nom_empleados_retirados`;
ALTER TABLE `nom_empleados_retirados` AUTO_INCREMENT = 1;
DELETE FROM `nom_epss`;
ALTER TABLE `nom_epss` AUTO_INCREMENT = 1;
DELETE FROM `nom_fondo_censan`;
ALTER TABLE `nom_fondo_censan` AUTO_INCREMENT = 1;
DELETE FROM `nom_tipo_horaex`;
ALTER TABLE `nom_tipo_horaex` AUTO_INCREMENT = 1;
DELETE FROM `nom_horas_ex_trab`;
ALTER TABLE `nom_horas_ex_trab` AUTO_INCREMENT = 1;
DELETE FROM `nom_tipo_incapacidad`;
ALTER TABLE `nom_tipo_incapacidad` AUTO_INCREMENT = 1;
DELETE FROM `nom_incapacidad`;
ALTER TABLE `nom_incapacidad` AUTO_INCREMENT = 1;
DELETE FROM `nom_indemniza_vac`;
ALTER TABLE `nom_indemniza_vac` AUTO_INCREMENT = 1;
DELETE FROM `nom_libranzas`;
ALTER TABLE `nom_libranzas` AUTO_INCREMENT = 1;
DELETE FROM `nom_licencia_luto`;
ALTER TABLE `nom_licencia_luto` AUTO_INCREMENT = 1;
DELETE FROM `nom_licenciasmp`;
ALTER TABLE `nom_licenciasmp` AUTO_INCREMENT = 1;
DELETE FROM `nom_licenciasnr`;
ALTER TABLE `nom_licenciasnr` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_bsp`;
ALTER TABLE `nom_liq_bsp` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_cesantias`;
ALTER TABLE `nom_liq_cesantias` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_compesatorio`;
ALTER TABLE `nom_liq_compesatorio` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_dias_lab`;
ALTER TABLE `nom_liq_dias_lab` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_dlab_auxt`;
ALTER TABLE `nom_liq_dlab_auxt` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_embargo`;
ALTER TABLE `nom_liq_embargo` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_empleado`;
ALTER TABLE `nom_liq_empleado` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_horex`;
ALTER TABLE `nom_liq_horex` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_incap`;
ALTER TABLE `nom_liq_incap` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_indemniza_vac`;
ALTER TABLE `nom_liq_indemniza_vac` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_libranza`;
ALTER TABLE `nom_liq_libranza` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_licluto`;
ALTER TABLE `nom_liq_licluto` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_licmp`;
ALTER TABLE `nom_liq_licmp` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_licnr`;
ALTER TABLE `nom_liq_licnr` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_parafiscales`;
ALTER TABLE `nom_liq_parafiscales` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_prestaciones_sociales`;
ALTER TABLE `nom_liq_prestaciones_sociales` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_prima`;
ALTER TABLE `nom_liq_prima` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_prima_nav`;
ALTER TABLE `nom_liq_prima_nav` AUTO_INCREMENT = 1;
DELETE FROM `nom_metodo_pago`;
ALTER TABLE `nom_metodo_pago` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_salario`;
ALTER TABLE `nom_liq_salario` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_segsocial_empdo`;
ALTER TABLE `nom_liq_segsocial_empdo` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_sindicato_aportes`;
ALTER TABLE `nom_liq_sindicato_aportes` AUTO_INCREMENT = 1;
DELETE FROM `nom_vacaciones`;
ALTER TABLE `nom_vacaciones` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_vac`;
ALTER TABLE `nom_liq_vac` AUTO_INCREMENT = 1;
DELETE FROM `nom_meses`;
ALTER TABLE `nom_meses` AUTO_INCREMENT = 1;
DELETE FROM `nom_nomina_pto_ctb_tes`;
ALTER TABLE `nom_nomina_pto_ctb_tes` AUTO_INCREMENT = 1;
DELETE FROM `nom_novedades_afp`;
ALTER TABLE `nom_novedades_afp` AUTO_INCREMENT = 1;
DELETE FROM `nom_riesgos_laboral`;
ALTER TABLE `nom_riesgos_laboral` AUTO_INCREMENT = 1;
DELETE FROM `nom_novedades_arl`;
ALTER TABLE `nom_novedades_arl` AUTO_INCREMENT = 1;
DELETE FROM `nom_novedades_eps`;
ALTER TABLE `nom_novedades_eps` AUTO_INCREMENT = 1;
DELETE FROM `nom_novedades_fc`;
ALTER TABLE `nom_novedades_fc` AUTO_INCREMENT = 1;
DELETE FROM `nom_otros_descuentos`;
ALTER TABLE `nom_otros_descuentos` AUTO_INCREMENT = 1;
DELETE FROM `nom_pago_dependiente`;
ALTER TABLE `nom_pago_dependiente` AUTO_INCREMENT = 1;
DELETE FROM `nom_rango_viaticos`;
ALTER TABLE `nom_rango_viaticos` AUTO_INCREMENT = 1;
DELETE FROM `nom_tipo_rubro`;
ALTER TABLE `nom_tipo_rubro` AUTO_INCREMENT = 1;
DELETE FROM `pto_tipo_recurso`;
ALTER TABLE `pto_tipo_recurso` AUTO_INCREMENT = 1;
DELETE FROM `pto_tipo_rubro`;
ALTER TABLE `pto_tipo_rubro` AUTO_INCREMENT = 1;
DELETE FROM `pto_cargue`;
ALTER TABLE `pto_cargue` AUTO_INCREMENT = 1;
DELETE FROM `nom_rel_rubro`;
ALTER TABLE `nom_rel_rubro` AUTO_INCREMENT = 1;
DELETE FROM `nom_resolucion_viaticos`;
ALTER TABLE `nom_resolucion_viaticos` AUTO_INCREMENT = 1;
DELETE FROM `nom_resoluciones`;
ALTER TABLE `nom_resoluciones` AUTO_INCREMENT = 1;
DELETE FROM `nom_retencion_fte`;
ALTER TABLE `nom_retencion_fte` AUTO_INCREMENT = 1;
DELETE FROM `nom_salarios_basico`;
ALTER TABLE `nom_salarios_basico` AUTO_INCREMENT = 1;
DELETE FROM `nom_soporte_ne`;
ALTER TABLE `nom_soporte_ne` AUTO_INCREMENT = 1;
DELETE FROM `nom_tipo_certificado`;
ALTER TABLE `nom_tipo_certificado` AUTO_INCREMENT = 1;
DELETE FROM `nom_valxvigencia`;
ALTER TABLE `nom_valxvigencia` AUTO_INCREMENT = 1;
DELETE FROM `nom_viaticos`;
ALTER TABLE `nom_viaticos` AUTO_INCREMENT = 1;
DELETE FROM `pto_actos_admin`;
ALTER TABLE `pto_actos_admin` AUTO_INCREMENT = 1;
DELETE FROM `pto_cdp_detalle`;
ALTER TABLE `pto_cdp_detalle` AUTO_INCREMENT = 1;
DELETE FROM `pto_clase_sia`;
ALTER TABLE `pto_clase_sia` AUTO_INCREMENT = 1;
DELETE FROM `pto_codigo_cgr`;
ALTER TABLE `pto_codigo_cgr` AUTO_INCREMENT = 1;
DELETE FROM `pto_crp`;
ALTER TABLE `pto_crp` AUTO_INCREMENT = 1;
DELETE FROM `pto_crp_detalle`;
ALTER TABLE `pto_crp_detalle` AUTO_INCREMENT = 1;
DELETE FROM `pto_cop_detalle`;
ALTER TABLE `pto_cop_detalle` AUTO_INCREMENT = 1;
DELETE FROM `pto_cpc`;
ALTER TABLE `pto_cpc` AUTO_INCREMENT = 1;
DELETE FROM `pto_fuente`;
ALTER TABLE `pto_fuente` AUTO_INCREMENT = 1;
DELETE FROM `pto_vigencias`;
ALTER TABLE `pto_vigencias` AUTO_INCREMENT = 1;
DELETE FROM `pto_seccion`;
ALTER TABLE `pto_seccion` AUTO_INCREMENT = 1;
DELETE FROM `pto_sector`;
ALTER TABLE `pto_sector` AUTO_INCREMENT = 1;
DELETE FROM `pto_terceros`;
ALTER TABLE `pto_terceros` AUTO_INCREMENT = 1;
DELETE FROM `pto_politica`;
ALTER TABLE `pto_politica` AUTO_INCREMENT = 1;
DELETE FROM `pto_siho`;
ALTER TABLE `pto_siho` AUTO_INCREMENT = 1;
DELETE FROM `pto_sia`;
ALTER TABLE `pto_sia` AUTO_INCREMENT = 1;
DELETE FROM `pto_situacion`;
ALTER TABLE `pto_situacion` AUTO_INCREMENT = 1;
DELETE FROM `pto_homologa_gastos`;
ALTER TABLE `pto_homologa_gastos` AUTO_INCREMENT = 1;
DELETE FROM `pto_homologa_ingresos`;
ALTER TABLE `pto_homologa_ingresos` AUTO_INCREMENT = 1;
DELETE FROM `pto_tipo_mvto`;
ALTER TABLE `pto_tipo_mvto` AUTO_INCREMENT = 1;
DELETE FROM `pto_mod`;
ALTER TABLE `pto_mod` AUTO_INCREMENT = 1;
DELETE FROM `pto_mod_detalle`;
ALTER TABLE `pto_mod_detalle` AUTO_INCREMENT = 1;
DELETE FROM `seg_garantias_compra`;
ALTER TABLE `seg_garantias_compra` AUTO_INCREMENT = 1;
DELETE FROM `seg_permisos_modulos`;
ALTER TABLE `seg_permisos_modulos` AUTO_INCREMENT = 1;
DELETE FROM `seg_soporte_fno`;
ALTER TABLE `seg_soporte_fno` AUTO_INCREMENT = 1;
DELETE FROM `tb_codificacion_unspsc`;
ALTER TABLE `tb_codificacion_unspsc` AUTO_INCREMENT = 1;
DELETE FROM `tb_fin_fecha`;
ALTER TABLE `tb_fin_fecha` AUTO_INCREMENT = 1;
DELETE FROM `tb_fin_periodos`;
ALTER TABLE `tb_fin_periodos` AUTO_INCREMENT = 1;
DELETE FROM `tb_tipo_tercero`;
ALTER TABLE `tb_tipo_tercero` AUTO_INCREMENT = 1;
DELETE FROM `tb_rel_tercero`;
ALTER TABLE `tb_rel_tercero` AUTO_INCREMENT = 1;
DELETE FROM `tes_tipo_cuenta`;
ALTER TABLE `tes_tipo_cuenta` AUTO_INCREMENT = 1;
DELETE FROM `tes_cuentas`;
ALTER TABLE `tes_cuentas` AUTO_INCREMENT = 1;
DELETE FROM `tmp_ctb_libaux`;
ALTER TABLE `tmp_ctb_libaux` AUTO_INCREMENT = 1;
DELETE FROM `nom_liq_contrato_emp`;
ALTER TABLE `nom_liq_contrato_emp` AUTO_INCREMENT = 1;
DELETE FROM `ctb_retencion_rango`;
ALTER TABLE `ctb_retencion_rango` AUTO_INCREMENT = 1;
DELETE FROM `ctb_causa_retencion`;
ALTER TABLE `ctb_causa_retencion` AUTO_INCREMENT = 1;
DELETE FROM `ctb_causa_costos`;
ALTER TABLE `ctb_causa_costos` AUTO_INCREMENT = 1;