("005","Alcalde","Directivo"),
("030","Alcalde Local","Directivo"),
("032","Consejero de Justicia","Directivo"),
("036","Auditor Fiscal de Contraloría","Directivo"),
("010","Contralor","Directivo"),
("035","Contralor Auxiliar","Directivo"),
("003","Decano de Escuela o Institución Tecnológica","Directivo"),
("007","Decano de Institución Universitaria","Directivo"),
("008","Decano de Universidad","Directivo"),
("009","Director Administrativo o Financiero o Técnico u Operativo","Directivo"),
("060","Director de Area Metropolitana","Directivo"),
("055","Director de Departamento Administrativo","Directivo"),
("028","Director de Escuela o de Instituto o de Centro de Universidad","Directivo"),
("065","Director de Hospital","Directivo"),
("016","Director Ejecutivo de Asociación de Municipios","Directivo"),
("050","Director o Gerente General de Entidad Descentralizada","Directivo"),
("080","Director Local de Salud","Directivo"),
("024","Director o Gerente Regional o Provincial","Directivo"),
("039","Gerente","Directivo"),
("085","Gerente Empresa Social del Estado","Directivo"),
("001","Gobernador","Directivo"),
("027","Jefe de Departamento de Universidad","Directivo"),
("006","Jefe de Oficina","Directivo"),
("015","Personero","Directivo"),
("017","Personero Auxiliar","Directivo"),
("040","Personero Delegado","Directivo"),
("043","Personero Local de Bogotá","Directivo"),
("071","Presidente Consejo de Justicia","Directivo"),
("042","Rector de Institución Técnica Profesional","Directivo"),
("048","Rector de Institución Universitaria o de Escuela o de Institución Tecnológica","Directivo"),
("067","Rector de Universidad","Directivo"),
("020","Secretario de Despacho","Directivo"),
("054","Secretario General de Entidad Descentralizada","Directivo"),
("058","Secretario General de Institución Técnica Profesional","Directivo"),
("064","Secretario General de Institución Universitaria","Directivo"),
("052","Secretario General de Universidad","Directivo"),
("066","Secretario General de Escuela o de Institución Tecnológica","Directivo"),
("073","Secretario General de Organismo de Control","Directivo"),
("097","Secretario Seccional o Local de Salud","Directivo"),
("025","Subcontralor","Directivo"),
("070","Subdirector","Directivo"),
("068","Subdirector Administrativo o Financiero o Técnico u Operativo","Directivo"),
("072","Subdirector Científico","Directivo"),
("074","Subdirector de Área Metropolitana","Directivo"),
("076","Subdirector de Departamento Administrativo","Directivo"),
("078","Subdirector Ejecutivo de Asociación de Municipios","Directivo"),
("084","Subdirector o Subgerente General de Entidad Descentralizada","Directivo"),
("090","Subgerente","Directivo"),
("045","Subsecretario de Despacho","Directivo"),
("091","Tesorero Distrital","Directivo"),
("094","Veedor Distrital","Directivo"),
("095","Viceveedor Distrital","Directivo"),
("099","Veedor Distrital Delegado","Directivo"),
("096","Vicerrector de Institución Técnica Profesional","Directivo"),
("098","Vicerrector de Institución Universitaria","Directivo"),
("057","Vicerrector de Escuela Tecnológica o de Institución Tecnológica","Directivo"),
("077","Vicerrector de Universidad","Directivo"),
("005","Asesor","Asesor"),
("115","Jefe de Oficina Asesora de Jurídica o de Planeación o de Prensa o de Comunicaciones.","Asesor"),
("215","Almacenista General","Profesional"),
("202","Comisario de Familia","Profesional"),
("203","Comandante de Bomberos","Profesional"),
("204","Copiloto de Aviación","Profesional"),
("227","Corregidor","Profesional"),
("260","Director de Cárcel","Profesional"),
("265","Director de Banda","Profesional"),
("270","Director de Orquesta","Profesional"),
("235","Director de Centro de Institución Universitaria","Profesional"),
("236","Director de Centro de Escuela Tecnológica","Profesional"),
("243","Enfermero","Profesional"),
("244","Enfermero Especialista","Profesional"),
("232","Director de Centro de Institución Técnica Profesional","Profesional"),
("233","Inspector de Policía Urbano Categoría Especial y 1ª Categoría","Profesional"),
("234","Inspector de Policía Urbano 2ª Categoría","Profesional"),
("206","Líder de Programa","Profesional"),
("208","Líder de Proyecto","Profesional"),
("209","Maestro en Artes","Profesional"),
("211","Médico General","Profesional"),
("213","Médico Especialista","Profesional"),
("231","Músico de Banda","Profesional"),
("221","Músico de Orquesta","Profesional"),
("214","Odontólogo","Profesional"),
("216","Odontólogo Especialista","Profesional"),
("275","Piloto de Aviación","Profesional"),
("222","Profesional Especializado","Profesional"),
("242","Profesional Especializado Área Salud","Profesional"),
("219","Profesional Universitario","Profesional"),
("237","Profesional Universitario Área Salud","Profesional"),
("217","Profesional Servicio Social Obligatorio","Profesional"),
("201","Tesorero General","Profesional"),
("335","Auxiliar de Vuelo","Tecnico"),
("303","Inspector de Policía 3ª a 6ª Categoría","Tecnico"),
("306","Inspector de Policía Rural","Tecnico"),
("312","Inspector de Tránsito y Transporte","Tecnico"),
("313","Instructor","Tecnico"),
("336","Subcomandante de Bomberos","Tecnico"),
("367","Técnico Administrativo","Tecnico"),
("323","Técnico Área Salud","Tecnico"),
("314","Técnico Operativo","Tecnico"),
("403","Agente de Tránsito","Asistencial"),
("407","Auxiliar Administrativo","Asistencial"),
("412","Auxiliar Área Salud","Asistencial"),
("470","Auxiliar de Servicios Generales","Asistencial"),
("472","Ayudante","Asistencial"),
("475","Bombero","Asistencial"),
("413","Cabo de Bomberos","Asistencial"),
("428","Cabo de Prisiones","Asistencial"),
("411","Capitán de Bomberos","Asistencial"),
("477","Celador","Asistencial"),
("480","Conductor","Asistencial"),
("482","Conductor Mecánico","Asistencial"),
("485","Guardián","Asistencial"),
("416","Inspector","Asistencial"),
("487","Operario","Asistencial"),
("490","Operario Calificado","Asistencial"),
("417","Sargento de Bomberos","Asistencial"),
("438","Sargento de Prisiones","Asistencial"),
("440","Secretario","Asistencial"),
("420","Secretario Bilingüe","Asistencial"),
("425","Secretario Ejecutivo","Asistencial"),
("438","Secretario Ejecutivo del Despacho del Alcalde","Asistencial"),
("430","Secretario Ejecutivo del Despacho del Gobernador","Asistencial"),
("419","Teniente de Bomberos","Asistencial"),
("457","Teniente de Prisiones","Asistencial");
